[package]
name = "amber-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }  # for our async runtime
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0.75"
iso8601-timestamp = "0.2.11"
config = "0.13.1"
chrono = "0.4.30"
dateparser = "0.2.0"
thiserror = "1.0.48"
clap = { version = "4.4.11", features = ["derive"] }
exitcode = "1.1.2"

[dev-dependencies]
tokio = { version = "1", features = ["rt", "macros"] }
wiremock = "0.5.19"
claim = "0.5.0"
surf = "2.3.2"
